version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: colorbandit
      POSTGRES_PASSWORD: colorbandit
      POSTGRES_DB: colorbandit
    volumes:
      - colorbandit_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  # backend:
  #   build: ./backend
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     DATABASE_URL: postgresql+psycopg2://colorbandit:colorbandit@db:5432/colorbandit
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
volumes:
  colorbandit_pgdata:
